config/routes.rb
DatingSite::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'static_pages#home'

  # polling
  get '/poll' => 'application#poll', defaults: { format: 'js' }

  # blocked_users
  resources :blocked_users

  # images
  get 'images_new' => 'image#new'
  post 'images' => 'images#create'

  # likes
  get 'likes' => 'likes#index'
  post 'likes(.:format)' => 'likes#create', defaults: { format: 'js' }
  delete 'likes/:id' => 'likes#destroy', as: 'like', defaults: { format: 'js' }

  # messages
  post 'messages/mass_destroy' => 'messages#mass_destroy'
  get 'messages/poll' => 'messages#poll', defaults: { format: 'js' }
  resources :messages

  # users
  resources :users do
    # pics
    resources :pics
  end

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id                   :integer          not null, primary key
#  sender_id            :integer
#  recipient_id         :integer
#  content              :text
#  created_at           :datetime
#  updated_at           :datetime
#  removed_by_sender    :boolean          default(FALSE)
#  removed_by_recipient :boolean          default(FALSE)
#  read                 :boolean          default(FALSE)
#

class Message < ActiveRecord::Base
  attr_accessor :recipient_username

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  before_validation :set_recipient

  validates_presence_of :sender, :recipient, :content
  validate :sender_does_not_equal_recipient
  validate :sender_not_blocked

  def other_person(user)
    sender == user ? recipient : sender
  end

  def remove_user(user)
    removed_by_sender = true if user == sender
    removed_by_recipient = true if user == recipient
    removed_by_sender && removed_by_recipient ? destroy : save
  end

  def self.remove_user(user, contacts)
    where(sender_id: user.id, recipient_id: contacts)
      .update_all(removed_by_sender: true)
    where(recipient_id: user.id, sender_id: contacts)
      .update_all(removed_by_recipient: true)
    where(removed_by_sender: true, removed_by_recipient: true).delete_all
  end

  private

  def set_recipient
    self.recipient = User.find_by_username(recipient_username) unless recipient
  end

  def sender_does_not_equal_recipient
    errors.add(:base, 'cannot message yourself') if :sender == :recipient
  end

  def sender_not_blocked
    if recipient.blocked.include? sender
      errors.add(:base, 'this user has blocked you')
    end
  end
end

app/controllers/messages_controller.rb
# Handles messages/conversations between users
class MessagesController < ApplicationController
  def new
    @message = Message.new
    @recipient = User.find(params[:recipient_id]) if params[:recipient_id]
  end

  def create
    @message = current_user.sent_messages.create(message_params)
    error = @message.errors.full_messages[0] unless @message.persisted?
    respond_to do |format|
      format.html do
        redirect_to :back, flash: (error ? { error: error } : {})
      end
      format.js do
        flash.now[:error] = error if error
      end
    end
  end

  def destroy
    redirect_to :back
  end

  def mass_destroy
    Message.remove_user(current_user, params[:user_ids])
    redirect_to messages_path
  end

  def index
    @conversation_headers =
      current_user.conversation_headers.paginate(page: params[:page])
  end

  def poll # format.js
    case params[:parent_action]
    when 'show'
      new_messages = current_user.received_messages.where(
        sender_id: params[:contact_id], read: false
      )
      @new_messages = new_messages.order('created_at ASC').all
      new_messages.update_all(read: true)
    else
    end
    render 'application/poll'
  end

  def show
    contact_id =
      if params[:contact_id]
        params[:contact_id]
      else
        message = Message.find(params[:id])
        message.sender_id == current_user.id ? message.recipient_id : message.sender_id
      end.to_i
    contact = User.find_by_id(contact_id) || DeletedUser.new(contact_id)
    populate_conversation(contact)
  end

  private

  def message_params
    params.require(:message)
      .permit(:sender_id, :recipient_username, :recipient_id, :content)
  end

  def populate_conversation(contact)
    @contact = contact
    @messages = current_user.conversation(contact)
    Message.where(sender_id: @contact.id, recipient_id: current_user.id)
      .update_all(read: true)
    @message = Message.new
  end
end

app/views/messages/_conversation_header.html.haml
- contact = conversation_header[:with]
- new_messages = conversation_header[:new_messages]
- last_message = conversation_header[:last_message]

%tr
  %td
    = check_box_tag 'user_ids[]', contact.id
  %td
    - if new_messages
      = link_to message_path(0, contact_id: contact.id) do
        %span.glyphicon.glyphicon-envelope
  %td
    - if contact.instance_of? User
      = link_to contact do
        = contact.username
    - else
      = contact.username
  %td
    = link_to message_path(0, contact_id: contact.id) do
      = truncate last_message.content, length: 20
  %td
    = time_since last_message.created_at

app/views/messages/_fields.html.haml
- if @contact.nil?
  = f.input :recipient_username
- else
  = f.hidden_field :recipient_id, value: @contact.id

= f.input :content, as: :text, input_html: { rows: 4 },
  label: "Message to #{ @contact.username unless @contact.nil?}"

= f.submit class: 'btn btn-primary', value: 'Send'

app/views/messages/_message.html.haml
- sender = message.sender_id == current_user.id ? current_user : contact

.message.panel.panel-default
  .panel-heading
    - if sender.instance_of? User
      = link_to sender.username, sender
    - else
      = sender.username
  .panel-body
    = simple_format message.content, sanitize: true

app/views/messages/create.js.erb
<% if @message.persisted? %>
  $('#conversation').append('<%= j render(partial: 'message', locals: { message: @message }) %>');
  $('#message_content').val('');
  conversation.scrollTop = conversation.scrollHeight;
<% else %>
  $('#flash_messages').html('<%= j render(partial: 'layouts/flash') %>');
  $('html, body').stop().animate({scrollTop: 0}, 'fast');
<% end %>

app/views/messages/index.html.haml
- provide :title, 'Messages'

= form_tag controller: "messages", action: "mass_destroy" do
  %table#message_table.table
    %thead
      %tr
        %th
        %th
        %th Who
        %th Last Message
        %th When
    %tbody
      - if @conversation_headers.blank?
        %tr
          %td{colspan: 5} No messages.
      - else
        = render partial: 'conversation_header', collection: @conversation_headers, as: :conversation_header
  = submit_tag 'Delete selected', class: 'btn btn-primary'
  .pull-right
    = will_paginate @conversation_headers

app/views/messages/new.html.haml
= simple_form_for @message do |f|

  = render 'messages/fields', f: f

app/views/messages/show.html.haml
- provide :title, "Conversation with #{@contact.username}"

= content_tag :div, id: 'conversation', :'data-contact_id' => @contact.id do
  = render @messages, contact: @contact

= simple_form_for @message, remote: true do |f|
  = render 'fields', f: f

:javascript
  var div = document.getElementById('conversation');
  div.scrollTop = div.scrollHeight;