config/routes.rb
DatingSite::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'static_pages#home'

  # polling
  get '/poll' => 'application#poll', defaults: { format: 'js' }

  # blocked_users
  resources :blocked_users

  # images
  get 'images_new' => 'image#new'
  post 'images' => 'images#create'

  # likes
  get 'likes' => 'likes#index'
  post 'likes(.:format)' => 'likes#create', defaults: { format: 'js' }
  delete 'likes/:id' => 'likes#destroy', as: 'like', defaults: { format: 'js' }

  # messages
  post 'messages/mass_destroy' => 'messages#mass_destroy'
  get 'messages/poll' => 'messages#poll', defaults: { format: 'js' }
  resources :messages

  # users
  resources :users do
    # pics
    resources :pics
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  username               :string(255)
#  zip_code               :string(255)
#  latitude               :float
#  longitude              :float
#  birthday               :datetime
#  religion               :integer          default(0)
#  smokes                 :integer          default(0)
#  drinks                 :integer          default(0)
#  drugs                  :integer          default(0)
#  political_orientation  :integer          default(0)
#  diet                   :integer          default(0)
#  ethnicity              :integer          default(0)
#  height                 :integer          default(0)
#  body_type              :integer          default(0)
#  eye_color              :integer          default(0)
#  hair_color             :integer          default(0)
#  headline               :string(255)      default("")
#  about_me               :text             default("")
#  looking_for            :text             default("")
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_mappable lat_column_name: :latitude,
                   lng_column_name: :longitude

  attr_accessor :feet, :inches

  # username validations
  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: 3..20,
            format: { with: WORD_CHARS }
  validates :zip_code,
            presence: true,
            length: { is: 5 },
            format: { with: INTEGERS }
  validate :zip_code_has_coords
  validate :over_18
  validates :headline, length: 0..50

  # likes me
  has_many :liked_by, class_name: 'Like', as: :likeable, dependent: :destroy
  has_many :likes_me, through: :liked_by, source: :user

  # I like
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :likeable,
                         source_type: 'User'

  # blocked users
  has_many :blocked_users, dependent: :destroy
  has_many :blocked, through: :blocked_users

  # blocking users
  has_many :blocking_users, class_name: 'BlockedUser',
                            foreign_key: :blocked_id, dependent: :destroy
  has_many :blocked_by, through: :blocking_users, source: :user

  # messages
  has_many :sent_messages, class_name: 'Message', foreign_key: :sender_id
  has_many :recipients, through: :sent_messages
  has_many :received_messages, class_name: 'Message',
                               foreign_key: :recipient_id
  has_many :senders, through: :received_messages

  # pics
  has_many :pics

  after_find :height_to_feet_and_inches
  before_save :set_coordinates
  before_save :feet_and_inches_to_height
  before_destroy :remember_id
  after_destroy :remove_pics_and_directories

  def get_info(type)
    info_string = "#{ type }_info"
    send(info_string.to_sym) || info_string.camelize.constantize.new
  end

  def pool
    User.where.not(id: blocked + blocked_by << id)
  end

  def default_pic(type = false)
    args = [:image_url]
    args << type if type
    pics.first.try(*args) || 'default_person.jpeg'
  end

  def conversation_headers
    new_messages = {}
    last_messages = {}
    senders = received_messages.includes(:sender)
      .where(removed_by_recipient: false).map do |message|
        new_messages[message.sender_id] = true unless message.read
        previous_message = last_messages[message.sender_id]
        if previous_message.nil? || message.created_at > previous_message.created_at
          last_messages[message.sender_id] = message
        end
        message.sender || DeletedUser.new(message.sender_id)
      end
    recipients = sent_messages.includes(:recipient)
      .where(removed_by_sender: false).map do |message|
        previous_message = last_messages[message.recipient_id]
        if previous_message.nil? || message.created_at > previous_message.created_at
          last_messages[message.recipient_id] = message
        end
        message.recipient || DeletedUser.new(message.recipient_id)
      end
    people = (senders + recipients).try(:uniq) || []
    people.map do |person|
      {
        with: person,
        new_messages: new_messages.fetch(person.id, false),
        last_message: last_messages.fetch(person.id)
      }
    end
  end

  def unread_message_count
    received_messages.where(read: false, removed_by_recipient: false).count
  end

  def conversation(contact)
    set = [contact.id, self.id]
    Message.where(sender_id: set, recipient_id: set).order('created_at ASC')
  end

  def new_blockers_count
    blocking_users.where(new: true).count
  end

  def new_likers_count
    liked_by.where(new: true).count
  end

  def region
    zip_code.nil? ? '' : zip_code.to_region
  end

  def age
    years_old = Date.today.year - birthday.year
    years_old -= 1 if Date.today < birthday.to_date + years_old.years
    years_old
  end

  private

  def zip_code_has_coords
    if zip_code.to_latlon.nil?
      errors.add(:zip_code, 'not found')
    end
  rescue
    errors.add(:zip_code, 'invalid')
  end

  def over_18
    errors.add(:birthday, 'must be over 18') if age < 18
  end

  def set_coordinates
    self.latitude = self.zip_code.to_lat.to_f
    self.longitude = self.zip_code.to_lon.to_f
  end

  def pluralize(number, word)
    "#{ number.to_s } #{ word }" + (number > 1 ? 's' : '')
  end

  def remember_id
    @id = id
  end

  def remove_pics_and_directories
    pics.where(user_id: @id).destroy_all
    begin
      FileUtils.remove_dir("#{Rails.root}/public/uploads/pic/#{@id}")
    rescue => e
      puts e.message
    end
  end

  def height_to_feet_and_inches
    self.feet = get_feet
    self.inches = get_inches
  end

  def feet_and_inches_to_height
    self.height = begin
      feet.to_i * 12 + inches.to_i
    rescue
      0
    end
  end

  def get_feet
    height / 12
  end

  def get_inches
    height % 12
  end

end

app/controllers/users_controller.rb
# Controls all user actions including update of all has_one associated objects.
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:destroy, :edit, :show, :update]
  before_action :correct_user?, only: [:edit, :update, :destroy]

  def destroy
    @user.destroy
    redirect_to root_path
  end

  def edit
  end

  def index
    pool = current_user.pool
    @search_form = SearchForm.new(params[:search_form] || {})
    @users = search(pool).paginate(page: params[:page])
  end

  def show
    check_if_blocked
    @user_pic = @user.default_pic
    @pic = Pic.new
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated.'
      redirect_to @user
    else
      flash[:error] = 'Invalid information.'
      redirect_to :back
    end
  end

  private

  def search(pool)
    max_distance = @search_form.max_distance
    min_birthday = DateTime.now - @search_form.max_age.to_i.years
    pool = pool.where('birthday >= ?', min_birthday)
    if @search_form.max_age.to_i < 99
      max_birthday = DateTime.now - @search_form.min_age.to_i.years
      pool = pool.where('birthday <= ?', max_birthday)
    end
    unless max_distance.blank? || max_distance == 'any'
      pool = pool.within(max_distance, origin: current_user)
    end
    pool
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user?
    redirect_to(root_path) unless current_user == @user
  end

  def user_params
    params.require(:user).permit(:feet, :inches, :ethnicity, :body_type, :eye_color, :hair_color, :religion, :political_orientation, :smokes, :drinks, :drugs, :headline, :about_me, :looking_for)
  end
end

app/views/users/_image_carousel.html.haml
#image_carousel.carousel.slide{:'data-ride' => 'carousel'}
  / Indicators
  %ol.carousel-indicators
    %li.active{data: {target: '#image_carousel', :'slide-to' => '0'}}
    %li.active{data: {target: '#image_carousel', :'slide-to' => '1'}}
    %li.active{data: {target: '#image_carousel', :'slide-to' => '2'}}

  / Wrapper for slides
  .carousel-inner
    .item.active
      = image_tag 'deviant_butter.jpg', alt: 'deviant butter'
      .carousel-caption deviant butter
    .item
      = image_tag 'hondas.jpg', alt: 'hondas'
      .carousel-caption hondas
    .item
      = image_tag 'old_school.jpg', alt: 'old school'
      .carousel-caption old school

  / Controls
  %a.left.carousel-control{href: "#image_carousel", :'data-slide' => "prev"}
    %span.glyphicon.glyphicon-chevron-left
  %a.right.carousel-control{href: "#image_carousel", :'data-slide' => "next"}
    %span.glyphicon.glyphicon-chevron-right

app/views/users/_like_unlike.html.haml
- if current_user.liked_users.include? user
  = link_to like_path(user, type: 'User'), method: :delete, remote: true, class: 'btn btn-danger' do
    Unlike
    %span.glyphicon.glyphicon-thumbs-down
- else
  = link_to likes_path(user, type: 'User'), method: :post, remote: true, class: 'btn btn-success' do
    Like
    %span.glyphicon.glyphicon-thumbs-up

app/views/users/_search.html.haml
= simple_form_for search_form, url: users_path, method: :get do |f|
  .row
    .col-lg-4
      = f.input :max_distance, collection: SearchForm::MAX_DISTANCE_OPTIONS, include_blank: false
    .col-lg-4
      = f.input :min_age, collection: (18..99).to_a, include_blank: false
    .col-lg-4
      = f.input :max_age, collection: (18..99).to_a, include_blank: false
  .row
    .col-sm-12
      = f.submit 'Search', class: 'btn btn-primary'

app/views/users/_section.html.haml
- info = user.public_send("#{section}_info")

.panel.panel-default
  .panel-heading
    %h4= "#{section.capitalize} Info"
  - if current_user == user
    .panel-body
      = link_to 'Edit', edit_user_path(current_user, section: section)
  - unless info.nil?
    %table.table
      %tbody
        - info.class.display_attributes.each do |attribute|
          %tr
            = raw populate_row(info, attribute) unless info.public_send(attribute) == 0

app/views/users/_user.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title
      %span.pull-left= link_to user.username, user
      %span.pull-right= "last activity: #{ time_since(user.updated_at) }"
    .clearfix
  .panel-body
    .row
      .col-sm-5.col-md-3
        = link_to user do
          .thumbnail
            = image_tag user.default_pic(:thumb)
      .col-sm-7.col-md-9
        %span.pull-left= "#{ user.age } years old"
        %span.pull-right= user.region
        .clearfix
        %br
        %p= user.headline

app/views/users/create_destroy.js.erb
$('#like_unlike').html('<%= j render(partial: 'users/like_unlike', locals: { user: @likeable_object }) %>');

app/views/users/edit.html.haml
%h2 Edit Profile

= simple_form_for @user, html: { method: :put } do |f|
  %h3 Physical
  .form-inputs
    .row
      .col-sm-12.col-md-6
        .row
          .col-sm-12
            %label.select.optional.control-label Height
        .row
          .col-sm-6
            = f.input *build_select(:feet, label: false, include_blank: 'feet')
          .col-sm-6
            = f.input *build_select(:inches, label: false, include_blank: 'inches')
      .col-sm-12.col-md-6
        = f.input *build_select(:ethnicity)
    .row
      .col-sm-12.col-md-6
        = f.input *build_select(:body_type)
      .col-sm-12.col-md-6
        = f.input *build_select(:eye_color)
    .row
      .col-sm-12.col-md-6
        = f.input *build_select(:hair_color)

  %h3 Social
  .form-inputs
    .row
      .col-sm-12.col-md-6
        = f.input *build_select(:religion)
      .col-sm-12.col-md-6
        = f.input *build_select(:political_orientation)
    .row
      .col-sm-12.col-md-6
        = f.input *build_select(:smokes)
      .col-sm-12.col-md-6
        = f.input *build_select(:drinks)
    .row
      .col-sm-12.col-md-6
        = f.input *build_select(:drugs)

  %h3 Essay
  .form-inputs
    = f.input :headline
    = f.input :about_me, as: :text, input_html: {rows: 10, class: 'tinymce'}
    = f.input :looking_for, as: :text, input_html: {rows: 10, class: 'tinymce'}

  .form-actions
    = f.submit 'Update', class: 'btn btn-primary'
    = link_to 'Cancel', :back, class: 'btn btn-default'

= tinymce

app/views/users/index.html.haml
- provide :title, 'Browse'

= render 'search', search_form: @search_form

- if @users.blank?
  %p No users match your search criteria.
- else
  = render @users

.pull-right
  = will_paginate @users

app/views/users/show.html.haml
- provide :title, @user.username

- provide :headline, @user.headline

- if @user == current_user
  .row
    .col-sm-12
      .pull-right
        = link_to 'Edit Profile', edit_user_path(current_user), class: 'btn btn-primary'
        = link_to 'Edit Account', edit_user_registration_path(current_user), class: 'btn btn-default'
.row
  .col-sm-6
    .pull-left
      = "#{ @user.age } years old"
  .col-sm-6
    .pull-right
      = @user.region
      %br
      %br
.row
  .col-sm-8
    .row
      .col-sm-8.col-sm-offset-2
        = link_to user_pics_path(user_id: @user.id) do
          = image_tag @user_pic, class: 'img-responsive'
    %br

    %h3= 'About'
    .panel.panel-default
      .panel-body
        = raw @user.about_me
    %h3 Looking for
    .panel.panel-default
      .panel-body
        = raw @user.looking_for


  .col-sm-4
    .panel.panel-default
      .panel-heading
        %h4 Physical Info
      .panel-body
        %table.table
          %tbody
            %tr
              %td Height
              %td= "#{ @user.feet }' #{ @user.inches }\""
            %tr
              %td Body Type
              %td= BODY_TYPE[@user.body_type]
            %tr
              %td Ethnicity
              %td= ETHNICITY[@user.ethnicity]
            %tr
              %td Hair Color
              %td= HAIR_COLOR[@user.hair_color]
            %tr
              %td Eye Color
              %td= EYE_COLOR[@user.eye_color]
    .panel.panel-default
      .panel-heading
        %h4 Social Info
      .panel-body
        %table.table
          %tbody
            %tr
              %td Religion
              %td= RELIGION[@user.religion]
            %tr
              %td Political Orientation
              %td= POLITICAL_ORIENTATION[@user.political_orientation]
            %tr
              %td Smokes
              %td= SMOKES[@user.smokes]
            %tr
              %td Drinks
              %td= DRINKS[@user.drinks]
            %tr
              %td Drugs
              %td= DRUGS[@user.drugs]

- unless current_user == @user
  .pull-left
    = link_to 'Send Message', new_message_path(recipient_id: @user), class: 'btn btn-primary'
    %span#like_unlike
      = render 'like_unlike', user: @user
  .pull-right
    = link_to "Block" , blocked_users_path(blocked_id: @user), method: :post, class: 'btn btn-danger'