config/routes.rb
DatingSite::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'static_pages#home'

  # polling
  get '/poll' => 'application#poll', defaults: { format: 'js' }

  # blocked_users
  resources :blocked_users

  # images
  get 'images_new' => 'image#new'
  post 'images' => 'images#create'

  # likes
  get 'likes' => 'likes#index'
  post 'likes(.:format)' => 'likes#create', defaults: { format: 'js' }
  delete 'likes/:id' => 'likes#destroy', as: 'like', defaults: { format: 'js' }

  # messages
  post 'messages/mass_destroy' => 'messages#mass_destroy'
  get 'messages/poll' => 'messages#poll', defaults: { format: 'js' }
  resources :messages

  # users
  resources :users do
    # pics
    resources :pics
  end

end

app/models/blocked_user.rb
# == Schema Information
#
# Table name: blocked_users
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  blocked_id :integer
#  created_at :datetime
#  updated_at :datetime
#  new        :boolean          default(TRUE)
#

class BlockedUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :blocked, class_name: 'User'

  validates_uniqueness_of :blocked, scope: :user
  validate :user_does_not_equal_blocked

  private

  def user_does_not_equal_blocked
    errors.add(:base, 'cannot block yourself') if :user == :blocked
  end
end

app/controllers/blocked_users_controller.rb
# Allows users to block/unblock fellow users.
# Blocked users cannot like, view, or message their blockers.
class BlockedUsersController < ApplicationController
  def index
    @blocked = current_user.blocked_users
    @blocked_by = current_user.blocking_users
    current_user.blocking_users.update_all(new: false)
  end

  def create
    blocked_id = params[:blocked_id]
    @blocked_user = current_user.blocked_users.create(blocked_id: blocked_id)
    if @blocked_user.persisted?
      current_user.liked_by.where(user_id: blocked_id).destroy_all
    end
    redirect_to users_path
  end

  def destroy
    @blocked_user = BlockedUser.find(params[:id])
    @blocked_user.destroy if @blocked_user.user == current_user
    redirect_to users_path
  end
end

app/views/blocked_users/_blocked_user.html.haml
- blocked = blocked_user.blocked
- user = blocked_user.user

.well
  .row
    .col-sm-6
      - if current_user == blocked
        = user.username
      - else
        = link_to blocked.username, blocked
    - unless current_user == blocked
      .col-sm-6
        = link_to "Unblock", blocked_user_path(blocked_user), method: :delete

app/views/blocked_users/index.html.haml
- provide :title, 'Unfortunate Encounters'

%ul#blocked_users.nav.nav-tabs
  %li.active
    %a{href: '#blocked_by', :'data-toggle' => 'tab'} Blocked By
  %li
    %a{href: '#blocking', :'data-toggle' => 'tab'} Blocking

.tab-content
  #blocked_by.tab-pane.active
    - if @blocked_by.blank?
      %h4 Congratulations, nobody arbitrarily hates you...yet. When they do, try to keep in mind that it's not actually you they hate; it's the thought of your existence intermingling with theirs.
    - else
      = render @blocked_by
  #blocking.tab-pane
    - if @blocked.blank?
      %h4 Stalkers are people too, people looking for any chance to make a suit out of you. Feel free to stow them in here.
    - else
      = render @blocked
  %br