config/routes.rb
DatingSite::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'static_pages#home'

  # polling
  get '/poll' => 'application#poll', defaults: { format: 'js' }

  # blocked_users
  resources :blocked_users

  # images
  get 'images_new' => 'image#new'
  post 'images' => 'images#create'

  # likes
  get 'likes' => 'likes#index'
  post 'likes(.:format)' => 'likes#create', defaults: { format: 'js' }
  delete 'likes/:id' => 'likes#destroy', as: 'like', defaults: { format: 'js' }

  # messages
  post 'messages/mass_destroy' => 'messages#mass_destroy'
  get 'messages/poll' => 'messages#poll', defaults: { format: 'js' }
  resources :messages

  # users
  resources :users do
    # pics
    resources :pics
  end

end

app/models/pic.rb
# == Schema Information
#
# Table name: pics
#
#  id         :integer          not null, primary key
#  image      :string(255)
#  caption    :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Pic < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :user

  validates_presence_of :image
  validate :within_user_pic_limit

  before_destroy :remember_id
  after_destroy :remove_id_directory

  private

  def remember_id
    @id = id
    @user = user
  end

  def remove_id_directory
    begin
      FileUtils.remove_dir("#{Rails.root}/public/uploads/pic/#{@user.id}/#{@id}")
    rescue => e
      puts e.message
    end
  end

  def within_user_pic_limit
    if user.pics.count >= PIC_LIMIT
      errors.add(:base, 'already have the max number of pics')
    end
  end
end

app/controllers/pics_controller.rb
# Handles user images
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :update, :destroy]
  before_action :correct_user?, only: [:update, :destroy]

  def create
    @pic = current_user.pics.build(pic_params)
    @valid = @pic.save
    flash[:error] = @pic.errors.full_messages.first unless @valid
    redirect_to :back
  end

  def destroy
    @pic.destroy
    respond_to do |format|
      format.html do
        redirect_to :back
      end
    end
  end

  def index
    @user = User.find(params[:user_id])
    check_if_blocked
    @thumbnails = @user.pics
    @pic = Pic.new
  end

  def show
    @user = @pic.user
    check_if_blocked
  end

  def update
    respond_to do |format|
      format.js do
        @valid = @pic.update(pic_params)
      end
    end
  end

  private

  def correct_user?
    redirect_to(root_path) unless current_user == @pic.user
  end

  def set_pic
    @pic = Pic.find(params[:id])
  end

  def pic_params
    params.require(:pic).permit(:image, :caption)
  end
end

app/views/pics/_carousel.html.haml
#image_carousel.carousel.slide{:'data-ride' => 'carousel'}
  / Indicators
  %ol.carousel-indicators
    %li.active{data: {target: '#image_carousel', :'slide-to' => '0'}}
    %li.active{data: {target: '#image_carousel', :'slide-to' => '1'}}
    %li.active{data: {target: '#image_carousel', :'slide-to' => '2'}}

  / Wrapper for slides
  .carousel-inner
    = render partial: 'pics/carousel_pic', collection: pics, as: :pic

  / Controls
  %a.left.carousel-control{href: "#image_carousel", :'data-slide' => "prev"}
    %span.glyphicon.glyphicon-chevron-left
  %a.right.carousel-control{href: "#image_carousel", :'data-slide' => "next"}
    %span.glyphicon.glyphicon-chevron-right

app/views/pics/_carousel_pic.html.haml
.item.active
  = image_tag pic.image_url
  - unless pic.caption.blank?
    .carousel-caption = pic.caption

app/views/pics/_fields.html.haml
.form-group
  = f.label :image, 'Select an image'
  = f.file_field :image
= f.input :caption
= f.submit 'Upload', class: 'btn btn-default'

app/views/pics/_index.html.haml
= render partial: 'pics/thumbnail', collection: thumbnails, as: :thumbnail, locals: { show: true }

app/views/pics/_thumbnail.html.haml
.col-sm-6.col-md-4
  = link_to user_pic_path(thumbnail, user_id: thumbnail.user_id) do
    .thumbnail{id: "pic_#{thumbnail.id}"}
      = image_tag thumbnail.image_url(:thumb), :'data-src' => 'holder.js/300x200', alt: 'loading?'
      .caption
        %p= thumbnail.caption.presence || ''
  - if current_user == thumbnail.user
    .pull-right
      = link_to 'Edit', "#edit_pic_modal_#{thumbnail.id}", :'data-toggle' => 'modal'
      = link_to 'Delete', user_pic_path(thumbnail.id, user_id: thumbnail.user_id), method: :delete

- if current_user == thumbnail.user
  .modal.fade{id: "edit_pic_modal_#{thumbnail.id}", role: 'dialog', aria: {hidden: true}}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{:'data-dismiss' => "modal", :'aria-hidden' => true} &times;
          %h4.modal-title Edit Pic
        .modal-body
          = simple_form_for thumbnail, url: user_pic_path(thumbnail.id, user_id: thumbnail.user_id), action: :patch, remote: true do |f|
            = f.input :caption
            = f.submit 'Update Pic', class: 'btn btn-primary'

app/views/pics/index.html.haml
- provide :title, "#{ @user == current_user ? 'Your' : (@user.username + "'s") } photos"

- if current_user == @user
  .row
    .col-xs-12.col-sm-8.col-md-6
      = simple_form_for @pic, url: user_pics_path(user_id: current_user), html: { multipart: true } do |f|
        = render 'fields', f: f
.row
  = render 'index', thumbnails: @thumbnails

app/views/pics/show.html.haml
= image_tag @pic.image_url, class: 'image-show img-responsive'
%p= @pic.caption

app/views/pics/update.js.erb
$('#edit_pic_modal_<%= @pic.id %>').modal('hide');
<% if @valid %>
  $('#pic_<%= @pic.id %>').find('p').html('<%= j @pic.caption %>');
<% end %>